### ISSUE TITLE
PR: Add support for `eslint-plugin-compat`

### ISSUE THREAD

**Issue by amilajack** [uber-web/uber-eslint#12]
[This eslint plugin](http://github.com/amilajack/eslint-plugin-compat) lints against APIs that are only supported by target browsers 🎉 Would a PR for this be welcome?

**Here's a demo of it in action**

![demo of plugin usage](https://raw.githubusercontent.com/amilajack/eslint-plugin-compat/master/eslint-plugin-compat-demo.gif)

**Comment by dawsonbotsford** [comment]
@amilajack Seems like an interesting idea, but since the modules contained in this repo are used in both server-side and client-side code, I don't think it's generic enough. Would this behave poorly for server-side code?

**Comment by amilajack** [comment]
Even if the plugin is run on server side code, it should still perform well. The plugin runs only on MemberExpressions (ex: `WebAssembly.compile()` and NewExpressions (ex: `new IntersectionObserver(() => {})`)). If MemberExpression or NewExpression matches a specific identifier, it will read the corresponding caniuse record. So essentially, it only looks up caniuse records if and only if a member or new expression matches a given identifier (ex. `fetch`, `WebAssembly`, etc).

**Comment by dawsonbotsford** [comment]
For the time being, I don't see this as necessary here since we aren't creating WebAssembly nor purely client-side code. We appreciate you bringing up an issue instead of a PR, that was a great idea to save time and plan. Feel free to re-open this if conditions change.
